### ISSUE TITLE
Animate SVG

### ISSUE THREAD

**Issue by noblestreet** [noblestreet/animate-svg#1]
What we need is for both animals the tail to move slightly and smoothly (no more than 1cm movement), like a cat's tail AND ears to twitch.  

- The example svg displayes an example how a small part of the svg moves.
- Here is a more elaborate example : http://codepen.io/azevedo-252/pen/rVvMXX

original.html is base file to work from.
Work needs to be done in CSS (and JS only if necessary)

It will be used within a mobile application

**Comment by davidsemakula** [comment]
Hi @noblestreet 
Checkout https://github.com/noblestreet/animate-svg/pull/2

Let me know if any changes are required.
